"""empty message

Revision ID: 97dbeb0ae728
Revises: 
Create Date: 2018-10-11 19:14:19.395443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97dbeb0ae728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.drop_constraint('answers_ibfk_2', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'units', ['unit_id'], ['id'])
    op.drop_column('answers', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_ibfk_2', 'answers', 'users', ['user_id'], ['id'])
    op.drop_column('answers', 'unit_id')
    # ### end Alembic commands ###
